### ISSUE TITLE
Mode-selector positioning

### ISSUE THREAD

**Issue by AleCandido** [AleCandido/webcomponents#1]
The rule:
```css
... { position: absolute; }
```
looks suboptimal everywhere, I should try to replace it.
